# Generated by Django 5.0.6 on 2024-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slider_image1',
            field=models.ImageField(upload_to='media/slider/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slider_image2',
            field=models.ImageField(upload_to='media/slider/'),
        ),
    ]
