# Generated by Django 5.0.6 on 2024-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_blog_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(upload_to='media/logo/'),
        ),
    ]
